version: '3.0'

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env.development
    volumes:
      - .:/api
      - /api/node_modules
    ports:
      - '3000:3000'
    command: npm run start:dev
    depends_on:
      - migration
    links:
      - postgres
    restart: always

  postgres:
    container_name: postres
    image: postgres:14
    restart: always
    env_file:
      - .env.development
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/foo/pg_hba.conf
    command: ["postgres", "-c", "hba_file=/var/lib/foo/pg_hba.conf"]

  migration:
    build: .
    image: api
    command: npm run migrate:up:dev
    volumes:
      - .:/api
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  pgdata: